# Generated by Django 2.0.7 on 2018-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_letter_current_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_id',
            field=models.PositiveIntegerField(),
        ),
    ]
